### PR TITLE
chore: changing design tokens

### PR DESCRIPTION
**Pull request by pedronauck**

### CODE REVIEW

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
can we add `cursor:pointer` to "CardItem" clickable version ?
https://user-images.githubusercontent.com/8636507/236354657-65ba8b7e-9ad3-45a2-a0ac-5933bbc6d6e3.mov

**Comment by matteopetrani** [comment]
image

# COLORS
semantic/solid/*/color tokens are misaligned with the codebase.

For example:
token semantic/solid/base/color = {white}
--colors-semanticSolidBaseColor: #000000

**Comment by matteopetrani** [comment]
# Possibile inconsistencies

image
Above: Card 

Below: Dialog

The two are very similar and can become easily one single component with variants. 
Is there a reason for these little variances? 

Thanks!

**Comment by matteopetrani** [comment]
# Color issues
image

mismatch between tokens semantic/link/*/hover-color  and actual colors

**Comment by matteopetrani** [comment]
# Alert dialog
**DESIGN UPDATED**
image

To differentiate it from cards and give it a more standard layout, I slightly adjusted the alert dialog. 

Subject to review

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
