### PR TITLE
chore: fork stitches and improve it

### PR DESCRIPTION
**Pull request by pedronauck**
This pull request intends to copy stitches since it's unmaintained. Some modifications I made:

- [x] Improve type system
- [x] Improve generated class
- [x] Use the version from [this pull request](https://github.com/stitchesjs/stitches/pull/1115)

### CODE REVIEW

**Review by luizstacio — CHANGES_REQUESTED** [review]
I think we should not release package stitches. We should probably bundle together with fuel-ui and fuel-react.

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
I agree stitches packages should be private (not released) and only accessible when developing fuel-ui locally

**Comment by LuizAsFight** [comment]
card is looking too big (spacings and header text) is it expected and part of our design system? if not let's fix

image

**Comment by LuizAsFight** [comment]
even simplest card is looking too big with too much spacing 
image

**Comment by LuizAsFight** [comment]
it's looking pretty decent @pedronauck congratz

did you test if it still works with linking locally to `fuels-wallet` repo ? would be nice to check

**Comment by pedronauck** [comment]
> card is looking too big (spacings and header text) is it expected and part of our design system? if not let's fix
> 
> image

This PR isn't intended to have any change in terms of design, it just has the fork of stitches. So, all these design specs are the same as the old version that is already published. But, of course, if this is not good we can change, but the ideal place to have this mentions should be here:

https://github.com/FuelLabs/fuel-ui/pull/228

**Review by LuizAsFight — APPROVED** [review]

**Pull request merged**
